{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 30,
   "id": "ce2f7706-ffb2-4b81-8f26-5fdde9ed27ba",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Homework Challenge Solution\n",
    "\n",
    "# Add our dependencies."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "id": "8275e6d7-8a80-4d30-8101-edea9fd721c2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "hi!\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import csv\n",
    "dir (os)\n",
    "\n",
    "# Assign a variable for the file to load and the path.\n",
    "file_to_load = os.path.join(\"election_results.csv\")\n",
    "\n",
    "# Open the election results and read the file.\n",
    "with open(file_to_load) as election_data:\n",
    "    print(\"hi!\") "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "id": "7b9af456-5086-4897-9697-713fa627ecd7",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Assign a variable for the file to load and the path.\n",
    "file_to_load = 'election_results.csv'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "id": "31c5e077-4376-4f7e-b29a-33fcbc325263",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Add a variable to save the file to a path.\n",
    "#file_to_save = os.path.join(\"Desktop/Election_Analysis\", \"election_analysis.txt\")\n",
    "file_to_save = \"election_analysis.txt\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "id": "9d22c522-993d-4b23-9a6a-f5ba8c88cfa6",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Initialize a total vote counter.\n",
    "total_votes = 0\n",
    "\n",
    "# Candidate Options and candidate votes.\n",
    "candidate_options = []\n",
    "candidate_votes = {}\n",
    "\n",
    "# 1: Create a county list and county votes dictionary.\n",
    "county_options = []\n",
    "county_votes = {}\n",
    "\n",
    "# Track the winning candidate, vote count and percentage\n",
    "winning_candidate = \"\"\n",
    "winning_count = 0\n",
    "winning_county = 0\n",
    "winning_percentage = 0\n",
    "winning_c_percentage = 0\n",
    "\n",
    "# 2: Track the largest county and county voter turnout.\n",
    "lrg_turnout_county = \"\"\n",
    "lrg_turn_count = 0"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "id": "f5c1a1ed-6fc6-4730-bdfb-dad2642f02d2",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Read the csv and convert it into a list of dictionaries\n",
    "with open(file_to_load) as election_data:\n",
    "    reader = csv.reader(election_data)\n",
    "\n",
    "    # Read the header\n",
    "    header = next(reader)\n",
    "\n",
    "    # For each row in the CSV file.\n",
    "    for row in reader:\n",
    "\n",
    "        # Add to the total vote count\n",
    "        total_votes = total_votes + 1\n",
    "\n",
    "        # Get the candidate name from each row.\n",
    "        candidate_name = row[2]\n",
    "\n",
    "        # 3: Extract the county name from each row.\n",
    "        county_name = row[1]\n",
    "\n",
    "\n",
    "        # If the candidate does not match any existing candidate add it to\n",
    "        # the candidate list\n",
    "        if candidate_name not in candidate_options:\n",
    "\n",
    "            # Add the candidate name to the candidate list.\n",
    "            candidate_options.append(candidate_name)\n",
    "\n",
    "            # And begin tracking that candidate's voter count.\n",
    "            candidate_votes[candidate_name] = 0\n",
    "\n",
    "        # Add a vote to that candidate's count\n",
    "        candidate_votes[candidate_name] += 1\n",
    "\n",
    "        # 4a: Write an if statement that checks that the\n",
    "        # county does not match any existing county in the county list.\n",
    "        if county_name not in county_options:\n",
    "\n",
    "            # 4b: Add the existing county to the list of counties.\n",
    "            county_options.append(county_name)\n",
    "\n",
    "            # 4c: Begin tracking the county's vote count.\n",
    "            county_votes[county_name] = 0\n",
    "\n",
    "\n",
    "        # 5: Add a vote to that county's vote count.\n",
    "        county_votes[county_name] += 1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "id": "e3c57acb-cdd1-47c5-8223-a6307b524bbf",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Election Results\n",
      "-------------------------\n",
      "Total Votes: 369,711\n",
      "-------------------------\n",
      "\n",
      "County Votes:\n",
      "Jefferson: 10.5% (38,855)\n",
      "Denver: 82.8% (306,055)\n",
      "Arapahoe: 6.7% (24,801)\n",
      "\n",
      "-------------------------\n",
      "Largest County Turnout: Denver\n",
      "Winning County Vote: 306,055\n",
      "Winning County Percentage: 82.8%\n",
      "-------------------------\n",
      "\n",
      "Candidate Percentage of Votes:\n",
      "-------------------------\n",
      "\n",
      "Charles Casper Stockham: 23.0% (85,213)\n",
      "\n",
      "Diana DeGette: 73.8% (272,892)\n",
      "\n",
      "Raymon Anthony Doane: 3.1% (11,606)\n",
      "\n",
      "-------------------------\n",
      "Winner: Diana DeGette\n",
      "Winning Vote Count: 272,892\n",
      "Winning Percentage: 73.8%\n",
      "-------------------------\n",
      "\n"
     ]
    }
   ],
   "source": [
    "# Save the results to our text file.\n",
    "with open(file_to_save, \"w\") as txt_file:\n",
    "\n",
    "    # Print the final vote count (to terminal)\n",
    "    election_results = (\n",
    "        f\"\\nElection Results\\n\"\n",
    "        f\"-------------------------\\n\"\n",
    "        f\"Total Votes: {total_votes:,}\\n\"\n",
    "        f\"-------------------------\\n\\n\"\n",
    "        f\"County Votes:\\n\")\n",
    "    print(election_results, end=\"\")\n",
    "\n",
    "    txt_file.write(election_results)\n",
    "\n",
    "    # 6a: Write a for loop to get the county from the county dictionary.\n",
    "    for county_name in county_votes:\n",
    "        # 6b: Retrieve the county vote count.\n",
    "        county = county_votes.get(county_name)\n",
    "        # 6c: Calculate the percentage of votes for the county.\n",
    "        county_percentage = float(county) / float(total_votes) * 100\n",
    "        county_results = (\n",
    "            f\"{county_name}: {county_percentage:.1f}% ({county:,})\\n\")\n",
    "\n",
    "         # 6d: Print the county results to the terminal.\n",
    "        print(county_results, end=\"\")\n",
    "         # 6e: Save the county votes to a text file.\n",
    "        txt_file.write(county_results)\n",
    "         # 6f: Write an if statement to determine the winning county and get its vote count.\n",
    "        if (county > winning_county) and (county_percentage > winning_c_percentage):\n",
    "            winning_county = county\n",
    "            winning_c_candidate = county_name\n",
    "            winning_c_percentage = county_percentage\n",
    "\n",
    "    # 7: Print the county with the largest turnout to the terminal.\n",
    "    winning_county_summary = (\n",
    "        f\"\\n-------------------------\\n\"\n",
    "        f\"Largest County Turnout: {winning_c_candidate}\\n\"\n",
    "        f\"Winning County Vote: {winning_county:,}\\n\"\n",
    "        f\"Winning County Percentage: {winning_c_percentage:.1f}%\\n\"\n",
    "        f\"-------------------------\\n\\n\"\n",
    "        f\"Candidate Percentage of Votes:\\n\"\n",
    "        f\"-------------------------\\n\")\n",
    "    print(winning_county_summary)\n",
    "\n",
    "    # 8: Save the county with the largest turnout to a text file.\n",
    "    txt_file.write(winning_county_summary)\n",
    "\n",
    "    # Save the final candidate vote count to the text file.\n",
    "    for candidate_name in candidate_votes:\n",
    "\n",
    "        # Retrieve vote count and percentage\n",
    "        votes = candidate_votes.get(candidate_name)\n",
    "        vote_percentage = float(votes) / float(total_votes) * 100\n",
    "        candidate_results = (\n",
    "            f\"{candidate_name}: {vote_percentage:.1f}% ({votes:,})\\n\")\n",
    "\n",
    "        # Print each candidate's voter count and percentage to the\n",
    "        # terminal.\n",
    "        print(candidate_results)\n",
    "        #  Save the candidate results to our text file.\n",
    "        txt_file.write(candidate_results)\n",
    "\n",
    "        # Determine winning vote count, winning percentage, and candidate.\n",
    "        if (votes > winning_count) and (vote_percentage > winning_percentage):\n",
    "            winning_count = votes\n",
    "            winning_candidate = candidate_name\n",
    "            winning_percentage = vote_percentage\n",
    "\n",
    "    # Print the winning candidate (to terminal)\n",
    "    winning_candidate_summary = (\n",
    "        f\"-------------------------\\n\"\n",
    "        f\"Winner: {winning_candidate}\\n\"\n",
    "        f\"Winning Vote Count: {winning_count:,}\\n\"\n",
    "        f\"Winning Percentage: {winning_percentage:.1f}%\\n\"\n",
    "        f\"-------------------------\\n\")\n",
    "    print(winning_candidate_summary)\n",
    "\n",
    "    # Save the winning candidate's name to the text file\n",
    "    txt_file.write(winning_candidate_summary)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c6a2a470-73f2-4ed6-be3e-58fc81d6bfbe",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ef2800ed-cb77-4d1b-adc6-e3b520d26b11",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
